<?php

return [
	"invalid parameter" => "无效的参数",
	"validator `%s' not found" => "验证器`%s'不存在",
	"{0} didn't pass the validator `%s'" => "{0}没有通过验证器`%s'的验证",
	'validation data,rules must be an array' => '验证器参数和规则必须为数组',
	'desire' => [
		'validator' => [
			'messages' => [
				'required' => '{0}必填',
				'not_empty' => '{0}不能为空',
				'regex' => "{0}{1.3}",
				'equals' => "{0}须等于`{1.2}'",
				'date' => '{0}非有效的时间',
				'is_numeric' => '{0}必须是数字',
				'is_array' => '{0}必须是数组',
				'region_exist' => '{0}不存在',
			],
			'alias' => [
				'region_id' => '站点ID',
				'account_id' => '账号ID',
				'username' => '用户名',
				'passwd' => '密码',
				'mobile' => '手机号码',
				'email' => '邮箱',
			],
		],
	],
	"class `%s' not found" => "类[%s]加载失败",
	"include directory `%s' not exist" => "不存在加载的目录：`%s'",
	"parameter `%s' not exist" => "参数`%s'不存在",
	'invalid session save handler' => '无效的Session句柄',
	'CSRF security error' => "验证跨站请求伪造(Cross Site Request Forgery)失败，请重试！",
	//给 Desire_Application_Helper_Html:select 的 value 替换
	"controller file `%s' not exist" => "没找到控制器文件：`%s'",
	"load controller `%s.%s` failed" => "加载控制器[%s.%s]失败",
	"action `%s.%s.%s' not exist" => "处理器[%s.%s.%s]不存在",
	"effective cache in chain %s not found" => "缓存链%s中不存在有效的句柄",

	'Please Enter Your Information' => '登录平台',
	'Oh snap!' => '糟糕！',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
];